### ISSUE TITLE
Arrays: [] after type or identifer?

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/maestro#157]
The following is allowed for arrays:
```
real[] realValueSize7[7] = {1,2,3,4,5,6,7};
```

It seems like `real[]` creates the correct type, i.e. `AArrayType`.
`realvaluesize7[7]` makes it into `ARealNumericPrimitiveType`.

**Comment by CThuleHansen** [comment]
It seems like real[] makes it into an arraytype, whereas realvaluesize7[] makes it into an expression with a primitive type and an isarray property set to true

**Comment by nickbattle** [comment]
It's unusual that the syntax allows this. Is the LHS of an assignment the same syntax as an expression? In VDM, assignments have a completely different class of syntax on the LHS (a "state designator").

Intuitively, I would keep all the type-related syntax close to the type declaration (ie. "real").

**Comment by CThuleHansen** [comment]
Yes, thinking of whether it should be real[7]. 
Will discuss with kenneth tomorrow. Thank you for input.
Actually both is allowed in java, I think that is where it all originates, as we started with the lexer/parser for java.
```
      int[] a = {1,2,3};
      int b[] = {1,2,3};
```
is fine in Java

**Comment by nickbattle** [comment]
The original syntax comes from C, with declarations like "int array[5]", though you can refer to an anonymous array type as "int[]". This gets horribly complicated though, especially when you throw pointers into the mix, and functions that return pointers (as opposed to pointers to functions that return non-pointers)... it was awful. So they cleaned it up a lot in Java and I think moving the dimensions closer to the base type was one such improvement.

**Comment by nickbattle** [comment]
If you allow an explicit dimension, like "real[7] array = ...", then you should think about whether you are stating a type invariant (this array will always have precisely or at most 7 elements) or whether this is a storage allocation issue (the array will start at 7 elements, but can grow, like a Java Vector etc). Without a dimension, like "real[] array =" you're inferring the dimension size from the initializer, which may place constraints on it (eg. a literal, so the type checker knows its size, rather than getArray() which  returns an unknown size). Similarly with multi-dimensions, if you support them.

**Comment by CThuleHansen** [comment]
So I think we are going for `int a[7]`, because it is what people know from C and C++. We have not seen any languages that use `int[7] a` for example
