### ISSUE TITLE
Web API test actions often fails on Mac

### ISSUE THREAD

**Issue by FrederikPM** [INTO-CPS-Association/maestro#295]
Seems to be due to: "Failed to connect: ConnectionError" "raise Exception("Unable to connect to host")"

**Comment by CThuleHansen** [comment]
I think this is due to the port not being available, or waiting time too slow.
Do we scan for available ports before starting? (I think we do)
Can we increase the wait time?

**Comment by rudi** [comment]
> I think this is due to the port not being available, or waiting time too slow.
> Do we scan for available ports before starting? (I think we do)
> Can we increase the wait time?

Random drive-by comment, ignore as needed: scanning then trying to open a port is a race condition (what happens when you start multiple tests in parallel?).  You could open a listening socket on port 0 (which chooses a random free port) and communicate the port number out of band, e.g. by printing it to stderr; this is what we do to test the abs model api.

**Comment by CThuleHansen** [comment]
Thank you @rudi , makes sense. 
It sort of shifts the thing around, as currently Maestro is instructed to open on a specific port. But given 0, it could probably communicate this back.

**Comment by CThuleHansen** [comment]
@rudi worked like a charm ;)
