### ISSUE TITLE
Include VDM Check in UnitRelationShip

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/maestro#63]
When the environment is parsed VDMCheck should be executed to ensure the correctness of the Model Description files. However, it should be ocnfigurable whether to run VDMCheck or not.

Implementation is expected to occur in the UnitRelationShip class. 
The VDMCHeck repo is available at https://github.com/INTO-CPS-Association/FMI-VDM-Model/

Tagging @nickbattle the author of VDM Check, but I do not expect him to implement it.

**Comment by nickbattle** [comment]
From an earlier email:

Hi Casper,

The important thing to understand is that VDMCheck is a series of steps, only one of which is a VDM-SL model execution. This process is embodied in either a bash script, or a stand-alone Java program with static methods that call things in order. The steps are:

1. Extract the modelDescription.xml from the FMU ZIP file passed (unless raw XML is passed)
2. Call a Java class called FMI2SaxParser to (optionally) XSD-validate the XML against the FMI schema files, and turn the XML into VDM-SL structures that are equivalent.
3. Launch VDMJ with the FMI2 model plus the XML-converted-to-VDM structure and invoke the isValidFMIModelDescription function.
4. If there are errors, @OnFail annotations will produce standard output error messages and the exit code will be non-zero. Else there is no output and a zero exit code means success.
5. The script says "No errors found" or "Errors found", to be friendly :-)

So I would start by having a look at VDMCheck.java - INTO-CPS-Association/FMI-VDM-Model/FMI2_to_VDM/src/main/java/VDMCheck.java. The bash script in src/main/scripts/VDMCheck2.sh does the same things, but perhaps the Java is more useful?

When the process makes sense, we can talk about the details... :-)

If it would help, it would be possible to pass an *alternative* annotation jar, which does something more convenient than write to stdout - annotations are in a separate jar, and are intended to be user-provided, rather than being built into VDMJ.

Cheers,
-nick

**Comment by nickbattle** [comment]
It may help to have a look at the VDMJUnit tool, which allow us to evaluate VDM expressions from Java (it expects to be used with JUnit tests, but it works fine to simply evaluate expressions, like "isValidFMIModelDescription()").

See [VDMJUnit.pdf](https://github.com/INTO-CPS-Association/maestro/files/4812850/VDMJUnit.pdf)

**Comment by CThuleHansen** [comment]
@nickbattle thank you!
@prasadtalasila will most likely realise this!

**Comment by CThuleHansen** [comment]
@nickbattle would it be possibly to produce a fat jar that:
-  Can be included via maven or manually
- Can be invoked with i.e. checkModelDescription(VDMCheck.FMIVERSION2, path to XML file) and returns the results?

**Comment by nickbattle** [comment]
Presumably it would be possible, but is it saving us that much? Currently, you need three jars (fmi2vdm, vdmj and annotations) rather than one. If you want it packaged as a separate "command", isn't that what the current VDMCheck package does? Christian invokes it from Python. How does he do that?

**Comment by CThuleHansen** [comment]
@nickbattle certainly. Thank you. It is all good!
https://github.com/INTO-CPS-Association/pyfmu/blob/edc58f9f184e0eda41f8723edde33f0fe23fcbac/src/pyfmu/builder/validate.py#L120-L133

**Comment by clegaard** [comment]
> If you want it packaged as a separate "command", isn't that what the current VDMCheck package does? Christian invokes it from Python. How does he do that?

I invoke the jar as a subprocess with the -X flag and parse the resulting stdout to identify if the FMU is valid.
``` Python
        result = subprocess.run(["java", "-jar", jar_path, str(p)], capture_output=True)

    def _vdmcheck_no_errors(results):
        stdout_contains_no_error = b"no errors found" in results.stdout.lower()
        stderr_is_empty = results.stderr == b""
        error_code_ok = results.returncode == 0
        return stdout_contains_no_error and stderr_is_empty and error_code_ok
```

**Comment by prasadtalasila** [comment]
@clegaard Please provide a link to the file in the codebase.

**Comment by clegaard** [comment]
Same as Casper's, note that the current branch active branch is feature-pybind11, it will be back to master soon though ;)

https://github.com/INTO-CPS-Association/pyfmu/blob/b8f4240603f9ec9802e806fed746c87641c8b672/src/pyfmu/builder/validate.py#L181

**Comment by CThuleHansen** [comment]
https://github.com/INTO-CPS-Association/pyfmu/blob/a2f7067fb14a13cc50e8a4b653f67ddb7c5f6159/src/pyfmu/resources/resources.py#L42-L43

**Comment by CThuleHansen** [comment]
So Nick has agreed on getting vdmcheck on sonatype. An easier first step is to package it all into a fat jar and publish it to our own local package repository: https://overture.au.dk/artifactory/webapp/#/home

**Comment by nickbattle** [comment]
That link just gives me a blank page, but yes, I thought there was an Overture repository somewhere in AU. For the record, we will need to create packages for three jars:
* annotations
* fmi2vdm
* VDMJ

And there will be two version of fmi2vdm (for FMI2 and FMI3) and two version of VDMJ (the standard one and the high precision build).

**Comment by CThuleHansen** [comment]
> That link just gives me a blank page

Disable all add blockers and similar and try again 🙂

Works fine here, also on phone

**Comment by nickbattle** [comment]
Ah yes! That does work now I've turned off the Ad Blocker! :-)
